[package]
name = "maze_cruncher"
version = "1.5.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
image = "0.23.14"
ndarray = "0.15.0"
minifb = "0.19.3"
ux = "0.1.3"
queues = "1.0.0"